source "https://rubygems.org"

# Specify your gem's dependencies in <ProjectName | lowercase?paramcase>.gemspec
gemspec

gem "rake", "~> 12.0"

gem "minitest", "~> 5.0"
gem "minitest-reporters"
gem "minitest-profile"
gem 'simplecov', '~> 0.17.1'

gem "rubocop", "~> 1.3"
gem "rubocop-minitest", "~> 0.10.1"
gem "rubocop-performance", "~> 1.9"
